quest_status = {
    0 : 'In village',
    1 : 'Loading quest',
    2 : 'In Quest',
    3 : 'Victory',
    4 : 'Defeat',
    5 : 'Quest reset',
    6 : 'Quest time out',
    7 : 'Exit quest',
}


monster_names = {
    98   : 'Great Izuchi',
    54   : 'Great Baggi',
    107  : 'Kulu-Ya-Ku',
    59   : 'Great Wroggi',
    60   : 'Arzuros',
    61   : 'Lagombi',
    62   : 'Volvidon',
    91   : 'Aknosom',
    47   : 'Royal Ludroth',
    44   : 'Barroth',
    3    : 'Khezu',
    92   : 'Tetranadon',
    90   : 'Bishaten',
    102  : 'Pukei-Pukei',
    108  : 'Jyuratodus',
    4    : 'Basarios',
    93   : 'Somnacanth',
    1    : 'Rathian',
    42   : 'Barioth',
    109  : 'Tobi-Kadachi',
    89   : 'Magnamalo',
    100  : 'Anjanath',
    37   : 'Nargacuga',
    82   : 'Mizutsune',
    97   : 'Goss Harag',
    2    : 'Rathalos',
    95   : 'Almudron',
    57   : 'Zinogre',
    32   : 'Tigrex',
    7    : 'Diablos',
    94   : 'Rakna-Kadaki',
    24   : 'Kushala Daora',
    25   : 'Chameleos',
    27   : 'Teostra',
    23   : 'Rajang',
    118  : 'Bazelgeuse',
    96   : 'Wind Serpent Ibushi',
    99   : 'Thunder Serpent Narwa+',
    1379 : 'Narwa the Allmother+',
    1366 : 'Crimson Glow Valstrax',
    1852 : 'Apex Arzuros',
    1793 : 'Apex Rathian',
    1874 : 'Apex Mizutsune',
    1794 : 'Apex Rathalos',
    1799 : 'Apex Diablos',
    1849 : 'Apex Zinogre+',
    81   : 'Astalos',
    132  : 'Malzeno',
    19   : 'Daimyo Hermitaur',
    346  : 'Blood Orange Bishaten',
    134  : 'Garangolm',
    349  : 'Aurora Somnacanth',
    133  : 'Lunagaron',
    136  : 'Espinas',
    135  : 'Gaismagorm',
    71   : 'Gore Magala',
    77   : 'Seregios',
    351  : 'Magma Almudron',
    350  : 'Pyre Rakna-Kadaki',
    72   : 'Shagaru Magala',
    20   : 'Shogun Ceanataur',
    1303 : 'Furious Rajang',
    1369 : 'Scorned Magnamalo',
    1398 : 'Seething Bazelgeuse',
    514  : 'Silver Rathalos',
    513  : 'Gold Rathian',
    549  : 'Lucent Nargacuga',
}
